services:
    document_matcher:
        class: AppBundle\Service\DocumentMatcherService
        arguments: ["@doctrine.orm.entity_manager", "@rule_apply"]

    rule_apply:
        class: AppBundle\Service\RuleApplyService

    ocr:
        class: AppBundle\Service\OcrService

    repository.document:
        class: AppBundle\Repository\DocumentRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["AppBundle\\Entity\\Document"]