services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.document_matcher:
        class: AppBundle\Service\DocumentMatcherService
        arguments: [~, ~]

    app.ocr:
        class: AppBundle\Service\OcrService